/**
 * OpenAPI metadata checklist for new modules:
 * 1. Create `{module}/openapi.ts` with tag + operations + examples
 * 2. Enrich schemas with `description`
 * 3. Use `defineRoute` with full metadata
 * 4. Register tag in `shared/openapi/document-config.ts`
 * 5. Register response components in `shared/openapi/response-components.ts` if needed
 */
export const usersOpenApi = {
	tag: 'Users',
	operations: {
		listUsers: {
			operationId: 'listUsers',
			summary: 'List all users',
			description:
				'Returns a paginated list of all registered users. Pagination is not yet configurable — responses always use page 1 and pageSize 20.',
		},
		createUser: {
			operationId: 'createUser',
			summary: 'Create a new user',
			description: `
Creates a user account with **name**, **email**, and **role**.

- \`role\` accepts \`admin\` or \`member\`
- \`id\` and \`createdAt\` are generated by the server
      `.trim(),
		},
	},
	examples: {
		createUserRequest: {
			name: 'Ana Silva',
			email: 'ana@example.com',
			role: 'member' as const,
		},
		listUsersResponse: {
			data: [
				{
					id: '123e4567-e89b-12d3-a456-426614174000',
					name: 'Daniel Castro',
					email: 'daniel@example.com',
					role: 'admin' as const,
					createdAt: '2024-01-15T10:30:00.000Z',
				},
			],
			total: 1,
			page: 1,
			pageSize: 20,
		},
	},
} as const;
